import 'package:flutter/material.dart';
import 'package:udaan/Home/orderforms.dart';

class TermsOfUseSub extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Colors.blue,
        title: Text(
          'Terms Nov 2020',
          style: TextStyle(
            color: Colors.white,
          ),
        ),
        actions: <Widget>[
          Padding(
            padding: EdgeInsets.only(right: 20.0),
            child: GestureDetector(
              onTap: () {
                Navigator.push(
                    context,
                    MaterialPageRoute(
                        builder: (BuildContext context) => Orderforms()));
              },
              child: Icon(
                Icons.shopping_cart,
                color: Colors.white,
              ),
            ),
          ),
        ],
      ),
      body: Padding(
        padding: EdgeInsets.fromLTRB(20, 20, 20, 0),
        child: SingleChildScrollView(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Container(
                child: Text(
                  'Uploaded on 22nd December 2020',
                style: TextStyle(
                    fontSize: 17,
                  ),
                ),
              ),
              // Container(
              //   padding: EdgeInsets.fromLTRB(20, 10, 10, 0),
              //   child: Text(
              //     '1. BUY & SELL on their terms with secure payments and hassle-free logistics',
              //     style: TextStyle(
              //       fontSize: 17,
              //     ),
              //   ),
              // ),
              // Container(
              //   padding: EdgeInsets.fromLTRB(20, 10, 10, 0),
              //   child: Text(
              //     '2. BUY & SELL on their terms with secure payments and hassle-free logistics',
              //     style: TextStyle(
              //       fontSize: 17,
              //     ),
              //   ),
              // ),
              // Container(
              //   padding: EdgeInsets.fromLTRB(20, 10, 10, 0),
              //   child: Text(
              //     '3. BUY & SELL on their terms with secure payments and hassle-free logistics',
              //     style: TextStyle(
              //       fontSize: 17,
              //     ),
              //   ),
              // ),
              // Container(
              //   padding: EdgeInsets.fromLTRB(20, 10, 10, 0),
              //   child: Text(
              //     '4. BUY & SELL on their terms with secure payments and hassle-free logistics',
              //     style: TextStyle(
              //       fontSize: 17,
              //     ),
              //   ),
              // ),
              Container(
                child: Text(
                  '\nTERMS OF USE',
                  style: TextStyle(fontSize: 25, fontWeight: FontWeight.bold),
                ),
              ),
              Container(
                child: Text(
                  '\nClick here to refer to our privacy policy',
                style: TextStyle(
                    fontSize: 17,
                  ),
                ),
              ),
              Container(
                padding: EdgeInsets.fromLTRB(0, 10, 10, 0),
                child: Text(
                  'This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.',
                  style: TextStyle(
                    fontSize: 17,
                  ),
                ),
              ),
               Container(
                padding: EdgeInsets.fromLTRB(0, 10, 10, 0),
                child: Text(
                  'This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of domain name/ website [www.udaan.com] (“Website”), including the related mobile application (hereinafter referred to as “Platform”).',
                  style: TextStyle(
                    fontSize: 17,
                  ),
                ),
              ),
              Container(
                padding: EdgeInsets.fromLTRB(0, 10, 10, 0),
                child: Text(
                  'This document and such other rules and policies of the Platform (including but not limited to Return Shipments Policy, Undelivered Shipment Policy, Privacy Policy, Product Listing Policy, Infringement Policy) as may be amended from time to time are collectively referred to below as the “Terms”. We reserve the right, at our sole discretion, to change, modify, add or remove portions of these Terms, at any time without any prior written notice to You. By accessing, browsing, or otherwise using the Platform or using the Services, including following the posting of changes, User agrees to accept and be bound by the Terms (as may be amended from time to time). It is your responsibility to review these Terms periodically for any updates / changes. Please do not use the Services or access the Platform if you do not accept the Terms or are unable to be bound by the Terms.”).',
                  style: TextStyle(
                    fontSize: 17,
                  ),
                ),
              ),
              Container(
                padding: EdgeInsets.fromLTRB(20, 10, 10, 0),
                child: Text(
                  'I. BUY & SELL on their terms with secure payments and hassle-free logistics',
                  style: TextStyle(
                    fontSize: 17,
                  ),
                ),
              ),
              Container(
                padding: EdgeInsets.fromLTRB(20, 10, 10, 0),
                child: Text(
                  'II. BUY & SELL on their terms with secure payments and hassle-free logistics',
                  style: TextStyle(
                    fontSize: 17,
                  ),
                ),
              ),
              Container(
                padding: EdgeInsets.fromLTRB(20, 10, 10, 0),
                child: Text(
                  'III. BUY & SELL on their terms with secure payments and hassle-free logistics',
                  style: TextStyle(
                    fontSize: 17,
                  ),
                ),
              ),
              Container(
                padding: EdgeInsets.fromLTRB(0, 10, 10, 0),
                child: Text(
                  'This document and such other rules and policies of the Platform (including but not limited to Return Shipments Policy, Undelivered Shipment Policy, Privacy Policy, Product Listing Policy, Infringement Policy) as may be amended from time to time are collectively referred to below as the “Terms”. We reserve the right, at our sole discretion, to change, modify, add or remove portions of these Terms, at any time without any prior written notice to You. By accessing, browsing, or otherwise using the Platform or using the Services, including following the posting of changes, User agrees to accept and be bound by the Terms (as may be amended from time to time). It is your responsibility to review these Terms periodically for any updates / changes. Please do not use the Services or access the Platform if you do not accept the Terms or are unable to be bound by the Terms.”).',
                  style: TextStyle(
                    fontSize: 17,
                  ),
                ),
              ),
              Container(
                padding: EdgeInsets.fromLTRB(0, 10, 10, 0),
                child: Text(
                  'This document and such other rules and policies of the Platform (including but not limited to Return Shipments Policy, Undelivered Shipment Policy, Privacy Policy, Product Listing Policy, Infringement Policy) as may be amended from time to time are collectively referred to below as the “Terms”. We reserve the right, at our sole discretion, to change, modify, add or remove portions of these Terms, at any time without any prior written notice to You. By accessing, browsing, or otherwise using the Platform or using the Services, including following the posting of changes, User agrees to accept and be bound by the Terms (as may be amended from time to time). It is your responsibility to review these Terms periodically for any updates / changes. Please do not use the Services or access the Platform if you do not accept the Terms or are unable to be bound by the Terms.”).',
                  style: TextStyle(
                    fontSize: 17,
                  ),
                ),
              ),
              Container(
                child: Text(
                  '\n1. General Terms',
                  style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold),
                ),
              ),
              Container(
                padding: EdgeInsets.fromLTRB(20, 10, 10, 0),
                child: Text(
                  '1. Effective Date',
                  style: TextStyle(
                    fontSize: 17,fontWeight: FontWeight.bold
                  ),
                ),
              ),
              Container(
                padding: EdgeInsets.fromLTRB(35, 10, 10, 0),
                child: Text(
                  'These Terms of Use shall come into force with effect from 0000 hours of 27th November 2020.',
                  style: TextStyle(
                    fontSize: 17,
                  ),
                ),
              ),
              Container(
                padding: EdgeInsets.fromLTRB(20, 10, 10, 0),
                child: Text(
                  '2. APPLICATION AND ACCEPTANCE OF THE TERMS',
                  style: TextStyle(
                    fontSize: 17,fontWeight: FontWeight.bold
                  ),
                ),
              ),
              Container(
                padding: EdgeInsets.fromLTRB(35, 10, 10, 0),
                child: Text(
                  'i. Your use of the Platform and Udaan’s services, features, functionality, software and products (collectively the “Services” hereinafter) is subject to the terms and conditions contained in this document as well as the Privacy Policy, The Product Listing Policy, The Infringement Policy, The Return Shipments Policy, The Undelivered Shipment Policy and any other rules and policies of the Platform that Udaan may publish from time to time.',
                  style: TextStyle(
                    fontSize: 17,
                  ),
                ),
              ),
              Container(
                padding: EdgeInsets.fromLTRB(35, 10, 10, 0),
                child: Text(
                  'ii. You must read Udaan Privacy Policy which governs the collection, use, and disclosure of personal information about Users. You accept the terms of the Privacy Policy and agree to the use of the personal information about you in accordance with the Privacy Policy. ',
                  style: TextStyle(
                    fontSize: 17,
                  ),
                ),
              ),
               Container(
                padding: EdgeInsets.fromLTRB(20, 10, 10, 0),
                child: Text(
                  '3. PROVISION OF SERVICES',
                  style: TextStyle(
                    fontSize: 17,fontWeight: FontWeight.bold
                  ),
                ),
              ),
              Container(
                padding: EdgeInsets.fromLTRB(35, 10, 10, 0),
                child: Text(
                  'i. Your use of the Platform and Udaan’s services, features, functionality, software and products (collectively the “Services” hereinafter) is subject to the terms and conditions contained in this document as well as the Privacy Policy, The Product Listing Policy, The Infringement Policy, The Return Shipments Policy, The Undelivered Shipment Policy and any other rules and policies of the Platform that Udaan may publish from time to time.',
                  style: TextStyle(
                    fontSize: 17,
                  ),
                ),
              ),
              Container(
                padding: EdgeInsets.fromLTRB(35, 10, 10, 0),
                child: Text(
                  'ii. You must read Udaan Privacy Policy which governs the collection, use, and disclosure of personal information about Users. You accept the terms of the Privacy Policy and agree to the use of the personal information about you in accordance with the Privacy Policy. ',
                  style: TextStyle(
                    fontSize: 17,
                  ),
                ),
              ),
               Container(
                padding: EdgeInsets.fromLTRB(35, 10, 10, 0),
                child: Text(
                  'iii. You must read Udaan Privacy Policy which governs the collection, use, and disclosure of personal information about Users. You accept the terms of the Privacy Policy and agree to the use of the personal information about you in accordance with the Privacy Policy. ',
                  style: TextStyle(
                    fontSize: 17,
                  ),
                ),
              ),
               Container(
                padding: EdgeInsets.fromLTRB(35, 10, 10, 0),
                child: Text(
                  'iv. You must read Udaan Privacy Policy which governs the collection, use, and disclosure of personal information about Users. You accept the terms of the Privacy Policy and agree to the use of the personal information about you in accordance with the Privacy Policy. ',
                  style: TextStyle(
                    fontSize: 17,
                  ),
                ),
              ),
               Container(
                padding: EdgeInsets.fromLTRB(35, 10, 10, 0),
                child: Text(
                  'v. You must read Udaan Privacy Policy which governs the collection, use, and disclosure of personal information about Users. You accept the terms of the Privacy Policy and agree to the use of the personal information about you in accordance with the Privacy Policy. ',
                  style: TextStyle(
                    fontSize: 17,
                  ),
                ),
              ),
              Container(
                padding: EdgeInsets.fromLTRB(20, 10, 10, 0),
                child: Text(
                  '4.Eligibility',
                  style: TextStyle(
                    fontSize: 17,fontWeight: FontWeight.bold
                  ),
                ),
              ),
              Container(
                padding: EdgeInsets.fromLTRB(35, 10, 10, 0),
                child: Text(
                  'Your use of the Platform and Udaan’s services, features, functionality, software and products (collectively the “Services” hereinafter) is subject to the terms and conditions contained in this document as well as the Privacy Policy, The Product Listing Policy, The Infringement Policy, The Return Shipments Policy, The Undelivered Shipment Policy and any other rules and policies of the Platform that Udaan may publish from time to time.',
                  style: TextStyle(
                    fontSize: 17,
                  ),
                ),
              ),
              Container(
                padding: EdgeInsets.fromLTRB(35, 10, 10, 0),
                child: Text(
                  'You must read Udaan Privacy Policy which governs the collection, use, and disclosure of personal information about Users. You accept the terms of the Privacy Policy and agree to the use of the personal information about you in accordance with the Privacy Policy. ',
                  style: TextStyle(
                    fontSize: 17,
                  ),
                ),
              ),
              Container(
                padding: EdgeInsets.fromLTRB(20, 10, 10, 0),
                child: Text(
                  '5. USER ACCOUNTS AND VERIFICATION OF ACCOUNT',
                  style: TextStyle(
                    fontSize: 17,fontWeight: FontWeight.bold
                  ),
                ),
              ),
              Container(
                padding: EdgeInsets.fromLTRB(35, 10, 10, 0),
                child: Text(
                  'i. Your use of the Platform and Udaan’s services, features, functionality, software and products (collectively the “Services” hereinafter) is subject to the terms and conditions contained in this document as well as the Privacy Policy, The Product Listing Policy, The Infringement Policy, The Return Shipments Policy, The Undelivered Shipment Policy and any other rules and policies of the Platform that Udaan may publish from time to time.',
                  style: TextStyle(
                    fontSize: 17,
                  ),
                ),
              ),
              Container(
                padding: EdgeInsets.fromLTRB(35, 10, 10, 0),
                child: Text(
                  'ii. You must read Udaan Privacy Policy which governs the collection, use, and disclosure of personal information about Users. You accept the terms of the Privacy Policy and agree to the use of the personal information about you in accordance with the Privacy Policy. ',
                  style: TextStyle(
                    fontSize: 17,
                  ),
                ),
              ),
               Container(
                padding: EdgeInsets.fromLTRB(35, 10, 10, 0),
                child: Text(
                  'iii. You must read Udaan Privacy Policy which governs the collection, use, and disclosure of personal information about Users. You accept the terms of the Privacy Policy and agree to the use of the personal information about you in accordance with the Privacy Policy. ',
                  style: TextStyle(
                    fontSize: 17,
                  ),
                ),
              ),
               Container(
                padding: EdgeInsets.fromLTRB(35, 10, 10, 0),
                child: Text(
                  'iv. You must read Udaan Privacy Policy which governs the collection, use, and disclosure of personal information about Users. You accept the terms of the Privacy Policy and agree to the use of the personal information about you in accordance with the Privacy Policy. ',
                  style: TextStyle(
                    fontSize: 17,
                  ),
                ),
              ),
               Container(
                padding: EdgeInsets.fromLTRB(20, 10, 10, 0),
                child: Text(
                  '6. USERS GENERALLY',
                  style: TextStyle(
                    fontSize: 17,fontWeight: FontWeight.bold
                  ),
                ),
              ),
              Container(
                padding: EdgeInsets.fromLTRB(35, 10, 10, 0),
                child: Text(
                  'i. Your use of the Platform and Udaan’s services, features, functionality, software and products (collectively the “Services” hereinafter) is subject to the terms and conditions contained in this document as well as the Privacy Policy, The Product Listing Policy, The Infringement Policy, The Return Shipments Policy, The Undelivered Shipment Policy and any other rules and policies of the Platform that Udaan may publish from time to time.',
                  style: TextStyle(
                    fontSize: 17,
                  ),
                ),
              ),
              Container(
                padding: EdgeInsets.fromLTRB(35, 10, 10, 0),
                child: Text(
                  'ii. You must read Udaan Privacy Policy which governs the collection, use, and disclosure of personal information about Users. You accept the terms of the Privacy Policy and agree to the use of the personal information about you in accordance with the Privacy Policy. ',
                  style: TextStyle(
                    fontSize: 17,
                  ),
                ),
              ),
               Container(
                padding: EdgeInsets.fromLTRB(35, 10, 10, 0),
                child: Text(
                  'iii. You must read Udaan Privacy Policy which governs the collection, use, and disclosure of personal information about Users. You accept the terms of the Privacy Policy and agree to the use of the personal information about you in accordance with the Privacy Policy. ',
                  style: TextStyle(
                    fontSize: 17,
                  ),
                ),
              ),
               Container(
                padding: EdgeInsets.fromLTRB(35, 10, 10, 0),
                child: Text(
                  'iv. You must read Udaan Privacy Policy which governs the collection, use, and disclosure of personal information about Users. You accept the terms of the Privacy Policy and agree to the use of the personal information about you in accordance with the Privacy Policy. ',
                  style: TextStyle(
                    fontSize: 17,
                  ),
                ),
              ),
               Container(
                padding: EdgeInsets.fromLTRB(35, 10, 10, 0),
                child: Text(
                  'v. You must read Udaan Privacy Policy which governs the collection, use, and disclosure of personal information about Users. You accept the terms of the Privacy Policy and agree to the use of the personal information about you in accordance with the Privacy Policy. ',
                  style: TextStyle(
                    fontSize: 17,
                  ),
                ),
              ),
               Container(
                padding: EdgeInsets.fromLTRB(35, 10, 10, 0),
                child: Text(
                  'vi. You must read Udaan Privacy Policy which governs the collection, use, and disclosure of personal information about Users. You accept the terms of the Privacy Policy and agree to the use of the personal information about you in accordance with the Privacy Policy. ',
                  style: TextStyle(
                    fontSize: 17,
                  ),
                ),
              ),
              Container(
                padding: EdgeInsets.fromLTRB(50, 10, 10, 0),
                child: Text(
                  'a. You must read Udaan Privacy Policy which governs the collection, use, and disclosure of personal information about Users. You accept the terms of the Privacy Policy and agree to the use of the personal information about you in accordance with the Privacy Policy. ',
                  style: TextStyle(
                    fontSize: 17,
                  ),
                ),
              ),
              Container(
                padding: EdgeInsets.fromLTRB(65, 10, 10, 0),
                child: Text(
                  '1. You accept the terms of the Privacy Policy and agree to the use of the personal information about you in accordance with the Privacy Policy. ',
                  style: TextStyle(
                    fontSize: 17,
                  ),
                ),
              ),
              Container(
                padding: EdgeInsets.fromLTRB(65, 10, 10, 0),
                child: Text(
                  '2. You accept the terms of the Privacy Policy and agree to the use of the personal information about you in accordance with the Privacy Policy. ',
                  style: TextStyle(
                    fontSize: 17,
                  ),
                ),
              ),
              Container(
                padding: EdgeInsets.fromLTRB(65, 10, 10, 0),
                child: Text(
                  '3. You accept the terms of the Privacy Policy and agree to the use of the personal information about you in accordance with the Privacy Policy. ',
                  style: TextStyle(
                    fontSize: 17,
                  ),
                ),
              ),
              Container(
                padding: EdgeInsets.fromLTRB(65, 10, 10, 0),
                child: Text(
                  '4. You accept the terms of the Privacy Policy and agree to the use of the personal information about you in accordance with the Privacy Policy. ',
                  style: TextStyle(
                    fontSize: 17,
                  ),
                ),
              ),
              Container(
                padding: EdgeInsets.fromLTRB(65, 10, 10, 0),
                child: Text(
                  '5. You accept the terms of the Privacy Policy and agree to the use of the personal information about you in accordance with the Privacy Policy. ',
                  style: TextStyle(
                    fontSize: 17,
                  ),
                ),
              ),
              Container(
                padding: EdgeInsets.fromLTRB(65, 10, 10, 0),
                child: Text(
                  '6. You accept the terms of the Privacy Policy and agree to the use of the personal information about you in accordance with the Privacy Policy. ',
                  style: TextStyle(
                    fontSize: 17,
                  ),
                ),
              ),
              Container(
                padding: EdgeInsets.fromLTRB(65, 10, 10, 0),
                child: Text(
                  '7. You accept the terms of the Privacy Policy and agree to the use of the personal information about you in accordance with the Privacy Policy. ',
                  style: TextStyle(
                    fontSize: 17,
                  ),
                ),
              ),
              Container(
                padding: EdgeInsets.fromLTRB(65, 10, 10, 0),
                child: Text(
                  '8. You accept the terms of the Privacy Policy and agree to the use of the personal information about you in accordance with the Privacy Policy. ',
                  style: TextStyle(
                    fontSize: 17,
                  ),
                ),
              ),
              Container(
                padding: EdgeInsets.fromLTRB(65, 10, 10, 0),
                child: Text(
                  '9. You accept the terms of the Privacy Policy and agree to the use of the personal information about you in accordance with the Privacy Policy. ',
                  style: TextStyle(
                    fontSize: 17,
                  ),
                ),
              ),
              Container(
                padding: EdgeInsets.fromLTRB(65, 10, 10, 0),
                child: Text(
                  '10. You accept the terms of the Privacy Policy and agree to the use of the personal information about you in accordance with the Privacy Policy. ',
                  style: TextStyle(
                    fontSize: 17,
                  ),
                ),
              ),
              Container(
                padding: EdgeInsets.fromLTRB(50, 10, 10, 0),
                child: Text(
                  'a. You must read Udaan Privacy Policy which governs the collection, use, and disclosure of personal information about Users. You accept the terms of the Privacy Policy and agree to the use of the personal information about you in accordance with the Privacy Policy. ',
                  style: TextStyle(
                    fontSize: 17,
                  ),
                ),
              ),
              Container(
                padding: EdgeInsets.fromLTRB(50, 10, 10, 0),
                child: Text(
                  'b. You must read Udaan Privacy Policy which governs the collection, use, and disclosure of personal information about Users. You accept the terms of the Privacy Policy and agree to the use of the personal information about you in accordance with the Privacy Policy. ',
                  style: TextStyle(
                    fontSize: 17,
                  ),
                ),
              ),
              Container(
                padding: EdgeInsets.fromLTRB(50, 10, 10, 0),
                child: Text(
                  'c. You must read Udaan Privacy Policy which governs the collection, use, and disclosure of personal information about Users. You accept the terms of the Privacy Policy and agree to the use of the personal information about you in accordance with the Privacy Policy. ',
                  style: TextStyle(
                    fontSize: 17,
                  ),
                ),
              ),
              Container(
                padding: EdgeInsets.fromLTRB(50, 10, 10, 0),
                child: Text(
                  'd. You must read Udaan Privacy Policy which governs the collection, use, and disclosure of personal information about Users. You accept the terms of the Privacy Policy and agree to the use of the personal information about you in accordance with the Privacy Policy. ',
                  style: TextStyle(
                    fontSize: 17,
                  ),
                ),
              ),
              Container(
                padding: EdgeInsets.fromLTRB(50, 10, 10, 0),
                child: Text(
                  'e. You must read Udaan Privacy Policy which governs the collection, use, and disclosure of personal information about Users. You accept the terms of the Privacy Policy and agree to the use of the personal information about you in accordance with the Privacy Policy. ',
                  style: TextStyle(
                    fontSize: 17,
                  ),
                ),
              ),
              
            
             
            ],
          ),
        ),
      ),
    );
  }
}
